server:
  port: 8087

spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:5432/sidequest_db
    username: ${PG_USER:sidequest}
    password: ${PG_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

